### ISSUE TITLE
Struggling with deployment

### ISSUE THREAD

**Issue by GuillaumeBiessy** [doersino/nyum#12]
It's me again !

I am struggling with the deployment part.
I want to send the files to a free bookdown.org location, I have set up RSconnect and managed to send the index file manually from the editor. However I have issues with the deploy.sh.
I put guillaume_biessy78@bookdown.org in the config.yaml file and I get confirmation that the files are successfully sent somewhere, however when I go to bookdown.org I cannot see them.

Do you see a fix for this issue ? 

Also on a sidenote the Search feature does not seem to be working on my browser (both Chrome or Edge) but does work in the RStudio browser. I got a greyed search area and a "TypeError: Could not fetch" red warning.

**Comment by doersino** [comment]
Welcome back! :wink:

I don't think what you're trying is going to work – I'm not familar with with bookdown.org/RSconnect/RStudio, but from what I can tell, it doesn't provide an `rsync` "endpoint".

Perhaps some explanation might be useful: `deploy.sh` is a thin wrapper around the file syncing utility `rsync` (which is available on pretty much any system including yours, by the looks of it), instructing it to transfer the local `_site/` directory to the remote specified in `config.yaml`. As noted in the comment above this setting, the remote must take the shape of "USER@SERVER:PATH", and there must either be an `rsync` daemon running on the target or you must have SSH access to it. So `deploy.sh` isn't going to work for you – but as you mention, the files are successfully sent *somewhere* (without the `:PATH` bit, `rsync` transfers stuff locally), which should be a new folder in the current working directory called `guillaume_biessy78@bookdown.org/`.

Based on what I can tell from a quick scan of [the bookdown docs](https://bookdown.org/yihui/bookdown/rstudio-connect.html), the functionality built into RStudio/bookdown is designed to only allow documents created *with* bookdown to be pushed to bookdown.org. A look at the source code ([`bookdown::publish_book()`](https://github.com/rstudio/bookdown/blob/b66380e7c9a478edbebb3c21a0449a5c98f9bddb/R/publish.R) and [`rsconnect::deploySite()`](https://github.com/rstudio/rsconnect/blob/8c11a55bbbe111a4df1e37ddaeb6f19a86f32d39/R/deploySite.R) which does the actual deployment work) *suggests* that it actually just pushes the contents of the current working directory to bookdown.org, so maybe you could make it work? You might need to somehow navigate to the generated `_site/` directory first, I'm not sure. Again, I've never used any of this, just speculating based on the source code.

Another option is committing `_site` to a GitHub repository and using [GitHub Pages](https://pages.github.com) (in the linked guide, select "Project site" and then "Start from scratch" for the relevant instructions), which is what I'm doing for the demo. You can also use any standard web hosting provider.

(The fact that search doesn't work when viewing the site on your local file system is due to a security feature called [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), which prevents asynchronously loading `search.json` (you can disable it in some browsers, but it's not advisable). I should probably improve the error message!)

**Comment by GuillaumeBiessy** [comment]
Thank you very much for this very useful answer.
Indeed it looks like bookdown.org is not the only solution and definitely not the most convenient one in this case.

I set up a GitHub Pages account and managed to get everything working.
I can now access the page at https://guillaumebiessy.github.io/recettes/_site/ (I did not find a better way than having _site in the url).

From my understanding I cannot use the deploy.sh by setting deploy_remote : git@github.com:GuillaumeBiessy/recettes.git in the config.yaml file, maybe is has to do with git wanting a secure authentification that the deploy.sh does not integrate ?

Anyway everything is working in the end and that is the most important part, thank you !

**Comment by doersino** [comment]
No, `deploy.sh` isn't going to work – `rsync` and `git` are incompatible.

There's two ways to avoid having `_site/` in the URL if that's important to you:

1. Renaming `_site/` to `doc/s` and changing your GitHub Pages settings accordingly (I hope it'll one day support any path, right now it's either `/` or `docs/`).
2. Creating a new branch `gh-pages` in your repository, reconfiguring GitHub Pages to use that, and pushing the contents of `_site` to that branch.

Anyway, I'm glad things are finally working for you! 😊
