### ISSUE TITLE
Picture source (licensing) 

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#14]
Whenever I host pictures online I get very paranoid bc of possible licensing issues.
So I thought maybe the addition of a source for the image might calm my (an everyone else) nerves a little. 
Whats is your take on that so far?

**Comment by doersino** [comment]
I can add optional `image_author` and `image_source` fields to the YAML metadata.

The `image_source` would be an URL that the entire image links to, while the `image_author` would be shown in, say, the bottom left corner of the image, perhaps on hover only. Sound good?

But none of that will keep you from getting sued if you use copyrighted images from a particularly litigious publisher, of course. (Also, there should be no reason to use such imagery to begin with since the recipes you've collected would be dishes you frequently prepare yourself, so you can just snap a photo next time and use that. 😉)

**Comment by jlnrrg** [comment]
title and license might be handy to (https://www.pixsy.com/academy/image-user/correctly-attribute-images/)

lets just say I am more of a programmer and cook than a photograph 😆

**Comment by doersino** [comment]
For simplicity's sake, I don't want to introduce too many fields, so perhaps `image_attribution` instead of `image_author` might be better?

Good call on having to treat it differently on mobile. Perhaps it's best to always show it.

**Comment by jlnrrg** [comment]
yes that sounds good

Noah Doersing ***@***.***> schrieb am Di., 20. Apr. 2021,
09:44:
