### ISSUE TITLE
Ingredients amount change

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#15]
I know this is all about static generation, so this might be a tough call.
Anyway, most online cookbooks provide a feature to specify the serving size and calculate the ingredients up/down accordingly. 
I understand that this might be hard with a static side.
But maybe by using multiple files (one for each serving size) such a thing could be specified (even though it would be a ton of work administrative wise)

**Comment by doersino** [comment]
You could probably do this with JavaScript – provide a text field where the user can input a multiplier, then look for any numbers in the list of ingredients for each step and multiply them accordingly. But off the top of my head, here's a bunch of way this is tricky or can turn misleading quickly:

* Quantities like "½" would need to be normalized first.
* Some people write "1½" for "1.5", which is another case that requires normalization.
* Another special case would be required for things like "2-3 tbsp".
* Pluralization – if you multiply a recipe with 1.5, "1 cup" might turn into "1.5 cup", but should be "1.5 cups". While this might be doable for English, remember that this tool is intended to be language-agnostic.
* If there's only one of a thing, some recipe writers might omit the number, writing "egg" instead of "1 egg". You could assume a missing number to be 1 and multiply accordingly, but...
* ...things like "salt" and "pepper" are frequently just written as-is, which shouldn't be turned into "2 salt(s)" when a recipe is multiplied. Also, in this case, the instruction might say to "add a pinch of salt", which won't be nearly enough if multiplying a recipe by 5! Hard to detect.
* *There's probably much more I didn't think of.*

That's why I think adding a feature like this might do more harm than good – ingredient amounts might be off if specified in a non-standard way, potentially ruining a recipe. Then again, multiplying in your head on the fly is also error-prone. I assume proper recipe sites use well-tested, content-language-specific libraries for this, which is well outside the scope of this project.

You could always manually maintain two variants of a recipe – titled, say, "Lasagna (small)" and "Lasagna (large)" – with differing ingredient amounts. That already works fine and corresponds with your multiple-file idea, but as you say, it's a lot of work to maintain if you rework your recipes frequently.
