### ISSUE TITLE
Category Sub Pages / Filter

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#20]
It would be awesome if a limitation toward the category could be provided.
This could work is over the search bar (making the category searchable) or a separate page for each category.

Important extra is here the ability to click on the header breadcrumbs and arrive at the filtered result/ page.

![Screenshot from 2021-04-20 10-41-08](https://user-images.githubusercontent.com/77293597/115365805-03d74180-a1c5-11eb-9750-d9998c5ca0b5.png)

**Comment by doersino** [comment]
Search already works – enter (part of) a category name into the search field and the corresponding recipes will pop up.

---

Category pages are a bit trickier to do. The required data could be emitted as part of the metadata grouping step of `build.sh` – writing a JSON representation of each category into a separate JSON file in `_temp/`. Later, these JSON files could be converted to HTML using a similar template as is used for the index. Dealing with categories that aren't simple, no-spaces-and-alphanumeric strings imposes additional complexity: Pandoc's templating syntax doesn't provide any URL encoding facilities or similar, so getting from the category name to an appropriate filename for category pages (both during generation of said pages and for the purposes of linking to them from the recipe pages) needs to be done as part of `build.sh`.

*Probably not gonna tackle this any time soon.*

**Comment by jlnrrg** [comment]
How about including the search in the route.
Then you could just wrap the breadcrumb into an <a></a>

**Comment by doersino** [comment]
...?

**Comment by jlnrrg** [comment]
If the search bar accepts input from the url, one could create links that directly lead to reduction of the elements by using the search function.
This could be done e.g. with `URLSearchParams`.

**Comment by 10bass** [comment]
@jlnrrg For the search, you can add to the promise chain for fetch("search.json") by adding another .then before the .catch in search.js, to check a GET parameter and automatically search for it by filling the input and triggering the event. Here I'm just naming that parameter "search":

```javascript
    .then(() => {
        // if the browser supports URLSearchParams and input was provided, automatically search for it
        if (typeof URLSearchParams === "function") {
            const urlParams = new URLSearchParams(location.search);
            const urlSearch = urlParams.get('search');
            if (urlSearch) {
                searchInput.value = urlSearch;
                searchInput.focus();
                searchInput.dispatchEvent(new Event('input'));
            }
        }
    })
```

So calling /index.html?search=smoothie triggers the results dropdown and lets you add, correct, or just use the keyboard navigation.

Then for the breadcrumb, just modify recipe.template.html

from:
```html
$if(category)$$category$ <i>⟩</i>$endif$
```
to:
```html
$if(category)$<a href="/index.html?search=$category$">$category$</a> <i>⟩</i>$endif$
```
which will take you back to the index and search for that category text.

There's probably a better way to do that, but it works. If you wanted to get fancy you could tweak the script to search specific metadata with different keywords although that's more than I need it to do. I'm not in any rush to tackle a category page either.

@doersino Thanks so much for making this generator! The lightweight combination of bash, pandoc, and CSS/JS/templating has made this a lot of fun to tweak. So far I've added a frontmatter stub for tagging (not parsed/linked or anything, it's really just another field for me to search against & categorize with) and modified the search to treat each word as a Boolean AND, so "vegan cake" still returns a match as long they're both in the same metadata field.

**Comment by doersino** [comment]
> Thanks so much for making this generator! The lightweight combination of bash, pandoc, and CSS/JS/templating has made this a lot of fun to tweak.

That was the general idea! I'm very glad that I'm not the only weirdo who's into that kinda stuff. 😉

> ...and modified the search to treat each word as a Boolean AND, so "vegan cake" still returns a match as long they're both in the same metadata field

This sounds super useful – would you care to send a pull request for this? (No obligation, of course.) Your tagging feature is neat, too, but perhaps it's mostly relevant for your own use case.

---

I see that I should really implement category pages statically sooner rather than later – your JavaScript workaround is really inventive, but there's really no technical reason why this shouldn't be done statically (especially since search might turn up unrelated stuff, as well).

**Comment by 10bass** [comment]
Nice, I'm looking forward to seeing the categories! I think you implemented that in less time than it took me to agonize over my commit/PR. ;) Opened #22 for the search, obviously feel free to pick/discard bits as you like.

The tagging is definitely my own use weird case, especially in its current state it wouldn't offer much to anyone. I'm migrating from [BookStack ](https://github.com/BookStackApp/BookStack) and would otherwise miss the ability to search by tag - I had tagged recipes by primary ingredients & cuisine so I could for example search for [thai] [curry] [cashews].

**Comment by doersino** [comment]
I've done a fair bit of agonizing while working on this project – thank you for taking the time! I'll look at your pull request in a bit.

---

Alright, you can probably see the changes best by looking through `build.sh`.

What enabled this was the (perhaps obvious) realization that `build.sh` doesn't need to compile the recipes to HTML as the *first* step – that can wait until after metadata extraction and category shenanigans, at which time *faux* `urlencode`d category names can be fed into the compilation process using Pandoc's `--metadata` flag. This faux `urlencode`ing step requires using `awk`, which can be fraught, but both GNU `awk` and BSD `awk` seem to work fine.

I'm calling it *faux* since it's *basically* `urlencoding`, but it converts category names to lowercase, removes spaces, and *then* `urlencode`s but without adding "%" in front of code points – if it did, links would work but the filenames of the category pages would need to *not* be `urlencoded`, which is trouble (think of slashes etc.), and due to implementation details, non-ASCII characters would break things. Anyway, it works and I'm rambling. 😉

As far as I can tell, all this hasn't impacted build times by more than a few percent.
