### ISSUE TITLE
Ingredience Appearance Delimiter

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#8]
![Screenshot from 2021-03-25 18-11-29](https://user-images.githubusercontent.com/77293597/112514413-92f36400-8d95-11eb-9add-270b6f064812.png)

I noticed two improvement points.
1. if an ingredient position is too long it does not align with the amount anymore
2. The margin between a wordwrap is the same as for a new entry, making reading tougher
3. not really an issue, but if I just specify `* pepper` in the markdown, the ingredient gets pushed into the amount column. I worked around it by ```* ` ` pepper```

**Comment by doersino** [comment]
Both your first and third points are issues I also ran into during development and in my own use – I haven't been able to fix them and just try to avoid overly long words (I'm also German, mind you). 😉

The second one could be addressed by adding a small margin at the bottom of each list item, but that really inflates ingredient lists with no line breaks (which, at least for me, is the vast majority). I don't think it's worth the tradeoff. Another option is reducing the line height *and* adding a margin to compensate in the common case, but that throws things out of alignment due to differing font metrics. I also tried reducing the line height of all lines but the first, as follows:

```css
hr + ul li {
    line-height: 1;  /* smaller */
}
hr + ul li::first-line {
    line-height: 1.4;  /* normal */
}
```

but that doesn't have the intended effect either: While reducing the distance between first and subsequent lines as hoped, the next list item also gets closer, which negates the intended effect.

No good solution here, it seems, and since it's minor visual issue, please forgive me for marking it as *wontfix*.
